### ISSUE TITLE
Simplify map and document the steps

### ISSUE THREAD

**Issue by roata** [roataway/map-matcher-osrm-backend#1]
Document the process of simplifying the map structure, such that only the roads that meet these criteria are included:

- located in `{Chișinău, Ialoveni, Trușeni, Stăuceni, Codru}` (this list will be extended whenever RTEC grows their network, or when the buses are also a part of Roataway)
- used by public transport, specifically trolleybuses and buses (no minibuses/маршрутка)

The process must preferably be:
- a series of command line calls and queries
- that take `http://download.geofabrik.de/europe/moldova-latest.osm.pbf` at the input
- and provide `http://download.geofabrik.de/europe/moldova-latest-trimmed.osm.pbf` at the output
- such that this can be plugged into step#2 in the instructions given in the readme

**Comment by ralienpp** [comment]
Resolved by c522f40

**Comment by roata** [comment]
Closed by c522f40
